from rest_framework import serializers
from .models import Mechanic, ServiceRequest

#serializing data means converting python to JSON while sending data and JSON to python while recieving data. it also validates the data after converting
class MechanicSerializer(serializers.ModelSerializer):
    class Meta:
        model = Mechanic
        fields = ['id', 'name', 'phone', 'location', 'rating', 'is_open', 'services']


class ServiceRequestSerializer(serializers.ModelSerializer):
    class Meta:
        model = ServiceRequest
        fields = [
            'id', 'customer_name', 'customer_phone', 'vehicle_number',
            'mechanic', 'service', 'problem_description', 'status', 'created_at'
        ]
        read_only_fields = ['id', 'status', 'created_at']       #tells the function to only send these fields when requesting data but not accept it when recieving data because it is generated by the system